### ISSUE TITLE
Deprecation Warning in Symfony 3.3

### ISSUE THREAD

**Issue by spackmat** [mbence/OpenTBSBundle#8]
Hi, in Symfony 3.3, I get a Deprecation warning:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "opentbs" service to "MBence\OpenTBSBundle\Services\OpenTBS" instead.

This is because the services.yml looks like this:

````
services:
    opentbs:
        class:        MBence\OpenTBSBundle\Services\OpenTBS
        arguments:    []
````

Changing it to this resolves the warning:

````
services:
    MBence\OpenTBSBundle\Services\OpenTBS:
        arguments: []
    opentbs:
        alias: MBence\OpenTBSBundle\Services\OpenTBS
````

I don't know if this would BC break something (aliasing works at least for Symfony 2.7), but i would appreciate it, when such a change will be implemented before Symfony 4.0 is released. :)

Greets,
spackmat
